### ISSUE TITLE
Check for missing syntax nodes (not just error nodes)

### ISSUE THREAD

**Issue by hvithrafn** [wasm-lsp/wasm-lsp-server#4]

**Comment by darinmorrison** [comment]
It's not clear to me whether a `MISSING` node within the AST will register as the AST having an error. This is relevant because we only trigger parsing with `wast` if the root tree-sitter node reports that it contains an error. So it's possible we might be missing some errors that we should be reporting through diagnostics.

**Comment by hvithrafn** [comment]
Done now.
